version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "80:80"
  db:
    image: mariadb
    volumes:
      - wordpress-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
<<<<<<< HEAD
      MYSQL_DATABASE: fanwave-test
=======
      MYSQL_DATABASE: wordpress_lp
>>>>>>> c2153ee221b1a6d02020b881afc6f967c81613b8
    ports:
      - 3306:3306
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8095:80"
    volumes:
      - ./docker/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_ROOT_PASSWORD: root
<<<<<<< HEAD
      MYSQL_DATABASE: fanwave-test
=======
      MYSQL_DATABASE: wordpress_lp
>>>>>>> c2153ee221b1a6d02020b881afc6f967c81613b8
      UPLOAD_LIMIT: 300M
  # Wordpress
  wordpress:
    depends_on:
      - db
<<<<<<< HEAD
    image: wordpress:php8.2-fpm-alpine
=======
    image: wordpress:php7.4-fpm-alpine
>>>>>>> c2153ee221b1a6d02020b881afc6f967c81613b8
    volumes:
      - .:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
<<<<<<< HEAD
      WORDPRESS_DB_NAME: fanwave-test
=======
      WORDPRESS_DB_NAME: wordpress_lp
>>>>>>> c2153ee221b1a6d02020b881afc6f967c81613b8

networks:
  default:
    name: reverse_proxy

volumes:
  wordpress-db:
